# Refresh master table
If any of the source data tables are updated, re-run this notebook to update the master_latest.csv.
Before running, ensure that the updated source csv is added to the list of data files to merge.

### This is the original file

In [1]:
import pandas as pd
from typing import Dict

def add_columns_from_file(file_name: str, columns: Dict[str, str]):
    global df
    temp_df = pd.read_csv(file_name)
    # Drop extra columns from source file.
    extra_columns = [c for c in temp_df.columns if c not in list(columns.keys()) + ['quarter']]
    if extra_columns:
        temp_df = temp_df.drop(extra_columns, axis=1)
    temp_df.rename(columns=columns)
    existing_columns = [c for c in columns.values() if c != 'quarter' and c in df]
    if existing_columns:
        df = df.drop(existing_columns, axis=1)
    df = pd.merge(df, temp_df, how='left', on='quarter')

df = pd.read_csv(f'../data/master_original.csv')
df

,quarter,Time Period,Year,Quarter Label,Total Demand,"GDP (AUD, Millions)","Population (000,s)",Coal_Price (PCOALAUUSDM),Premium unleaded petrol (95 RON) (cpl),Regular unleaded petrol (91 RON) (cpl),Automotive diesel (cpl),Automotive LPG (cpl),Temperature(max),Temperature(avg),Temperature(min),Electricity,Renewables?
0,2010-01-01,2010-Q1,2010,Q1,49239561.29,314838,21964.10000,298.402058,136,126,125,62,29.94,23.83,18.54,NaN,NaN
1,2010-04-01,2010-Q2,2010,Q2,48247671.02,340575,22031.80000,317.381417,139,129,130,60,25.88,16.52,8.35,NaN,NaN
2,2010-07-01,2010-Q3,2010,Q3,50211015.42,345512,22104.40000,299.825672,135,124,128,54,22.98,15.06,8.13,NaN,NaN
3,2010-10-01,2010-Q4,2010,Q4,46514896.77,365403,22172.50000,339.576623,136,126,129,61,26.73,20.49,13.94,NaN,NaN
4,2011-01-01,2011-Q1,2011,Q1,48217913.16,341094,22268.80000,411.589309,148,137,142,73,29.44,23.65,18.63,NaN,NaN
5,2011-04-01,2011-Q2,2011,Q2,47830283.50,366641,22340.00000,387.850465,154,143,151,72,24.27,15.71,8.20,NaN,NaN
6,2011-07-01,2011-Q3,2011,Q3,48616230.64,372918,22432.80000,387.013149,152,142,146,69,23.50,14.46,6.96,NaN,NaN
7,2011-10-01,2011-Q4,2011,Q4,46137155.50,388419,22522.20000,368.834476,154,142,149,68,27.91,20.66,13.42,NaN,NaN
8,2012-01-01,2012-Q1,2012,Q1,47188663.11,358492,22640.90000,362.203525,156,145,150,75,28.16,22.67,17.48,NaN,NaN
9,2012-04-01,2012-Q2,2012,Q2,47011290.32,381023,22733.50000,306.927939,158,146,152,73,25.10,16.15,9.18,NaN,NaN
10,2012-07-01,2012-Q3,2012,Q3,47265632.34,379954,22833.90000,278.002062,152,139,146,63,24.27,14.74,6.52,NaN,NaN
11,2012-10-01,2012-Q4,2012,Q4,44883583.47,396614,22928.00000,270.181174,153,142,150,75,28.90,21.37,12.71,NaN,NaN
12,2013-01-01,2013-Q1,2013,Q1,46260200.22,369661,23043.00000,294.616218,155,145,150,70,29.80,23.27,18.03,NaN,NaN
13,2013-04-01,2013-Q2,2013,Q2,45318185.12,391216,23128.10000,276.001862,151,141,146,64,23.49,15.62,9.10,NaN,NaN
14,2013-07-01,2013-Q3,2013,Q3,45310078.97,393042,23220.20000,247.739707,160,150,155,73,24.44,15.29,7.89,NaN,NaN
15,2013-10-01,2013-Q4,2013,Q4,43773951.40,416029,23297.80000,263.251363,159,148,159,80,27.05,20.24,13.07,NaN,NaN
16,2014-01-01,2014-Q1,2014,Q1,45397804.12,386882,23406.20000,250.754279,165,154,161,89,28.89,22.79,17.41,NaN,NaN
17,2014-04-01,2014-Q2,2014,Q2,44165717.94,403742,23475.70000,234.703826,162,151,158,77,24.70,16.69,9.65,NaN,NaN
18,2014-07-01,2014-Q3,2014,Q3,45631896.93,402117,23562.90000,219.812086,157,147,155,74,22.17,14.02,6.16,NaN,NaN
19,2014-10-01,2014-Q4,2014,Q4,43431682.43,421533,23640.30000,203.477587,147,136,147,70,27.22,20.97,13.17,NaN,NaN
20,2015-01-01,2015-Q1,2015,Q1,44809031.10,392282,23745.60000,203.720401,131,120,129,60,28.47,22.65,17.22,42.7500,32236.09400
21,2015-04-01,2015-Q2,2015,Q2,44813067.37,408800,23816.00000,189.973805,148,136,132,59,22.92,15.50,8.78,46.7500,33778.54600
22,2015-07-01,2015-Q3,2015,Q3,46485333.26,411271,23904.30000,189.641866,146,133,130,56,21.36,13.68,6.74,50.7500,35320.99800
23,2015-10-01,2015-Q4,2015,Q4,44420746.58,427741,23984.60000,168.974559,137,125,126,59,27.96,21.09,13.98,54.7500,36863.45000
24,2016-01-01,2016-Q1,2016,Q1,46522035.50,398018,24103.40000,162.645765,137,112,114,60,29.20,23.03,18.13,58.7500,38405.90200
25,2016-04-01,2016-Q2,2016,Q2,44955022.24,421906,24190.90000,165.414388,128,119,115,62,25.90,17.07,9.90,68.0625,37773.44275
26,2016-07-01,2016-Q3,2016,Q3,46444310.88,423729,24297.50000,212.119179,127,115,118,59,21.61,14.86,8.80,77.3750,37140.98350
27,2016-10-01,2016-Q4,2016,Q4,43689492.06,456348,24385.10000,300.802345,134,123,124,64,28.50,20.69,11.76,86.6875,36508.52425
28,2017-01-01,2017-Q1,2017,Q1,46455202.23,429749,24511.40000,263.727626,141,130,130,71,30.15,23.84,18.90,96.0000,35876.06500
29,2017-04-01,2017-Q2,2017,Q2,44302363.68,449551,24592.60000,255.902458,138,126,128,70,23.74,15.88,9.15,95.0000,38437.75625
30,2017-07-01,2017-Q3,2017,Q3,45706381.00,451969,24690.10000,298.321382,135,123,126,68,23.94,14.50,6.64,94.0000,40999.44750
31,2017-10-01,2017-Q4,2017,Q4,43660453.74,472305,24759.00000,311.705485,149,136,133,77,28.68,20.92,14.31,93.0000,43561.13875
32,2018-01-01,2018-Q1,2018,Q1,45642401.29,446656,24881.80000,329.138013,149,136,139,80,29.77,23.12,17.83,92.0000,46122.83000
33,2018-04-01,2018-Q2,2018,Q2,44982003.65,473598,24963.30000,330.122883,159,146,149,78,25.47,16.18,8.02,95.6875,47630.73525
34,2018-07-01,2018-Q3,2018,Q3,45694022.87,476753,25067.40000,371.049886,159,148,154,80,21.69,14.02,6.14,99.3750,49138.64050
35,2018-10-01,2018-Q4,2018,Q4,43150248.30,501374,25146.10000,328.458643,155,143,157,83,28.05,20.71,13.81,103.0625,50646.54575
36,2019-01-01,2019-Q1,2019,Q1,46330705.49,471736,25264.90000,306.428339,143,131,143,72,30.21,23.63,18.32,106.7500,52154.45100
37,2019-04-01,2019-Q2,2019,Q2,44227126.72,500179,25334.80000,255.958750,159,146,149,76,24.82,16.28,8.93,98.3125,54429.86425
38,2019-07-01,2019-Q3,2019,Q3,45208703.31,503289,25438.10000,214.543767,156,142,146,72,23.28,14.51,7.68,89.8750,56705.27750
39,2019-10-01,2019-Q4,2019,Q4,42916303.02,522443,25520.50000,209.387979,164,150,148,71,28.81,20.87,12.93,81.4375,58980.69075
40,2020-01-01,2020-Q1,2020,Q1,44723503.36,488115,25627.90000,213.361218,154,139,145,77,29.05,22.65,16.74,73.0000,61256.10400
41,2020-04-01,2020-Q2,2020,Q2,43321142.35,470751,25649.20000,173.771068,125,110,120,70,24.93,15.72,8.32,69.8750,64578.20875
42,2020-07-01,2020-Q3,2020,Q3,44607685.65,488221,25633.30000,155.060387,137,123,118,70,22.74,14.50,7.97,66.7500,67900.31350
43,2020-10-01,2020-Q4,2020,Q4,41565582.03,531962,25630.70000,201.605705,139,123,117,69,27.33,20.66,13.45,63.6250,71222.41825
44,2021-01-01,2021-Q1,2021,Q1,36153608.61,513235,25653.00000,278.711972,149,134,126,76,27.84,22.06,17.53,60.5000,74544.52300
45,2021-04-01,2021-Q2,2021,Q2,NaN,555484,25685.40000,334.207743,159,143,135,80,NaN,NaN,NaN,79.8125,77185.01025
46,2021-07-01,2021-Q3,2021,Q3,NaN,547326,25704.00000,514.889471,169,153,145,82,NaN,NaN,NaN,99.1250,79825.49750
47,2021-10-01,2021-Q4,2021,Q4,NaN,590493,25771.40000,600.007746,180,164,160,96,NaN,NaN,NaN,118.4375,82465.98475
48,2022-01-01,2022-Q1,2022,Q1,NaN,572077,25909.90000,857.687492,197,182,182,101,NaN,NaN,NaN,137.7500,85106.47200
49,2022-04-01,2022-Q2,2022,Q2,NaN,623325,26014.40000,1180.637111,204,189,206,101,NaN,NaN,NaN,NaN,NaN
50,2022-07-01,2022-Q3,2022,Q3,NaN,624333,26161.80000,1348.857769,195,180,210,96,NaN,NaN,NaN,NaN,NaN
51,2022-10-01,2022-Q4,2022,Q4,NaN,662870,26312.20000,1222.854427,199,184,222,95,NaN,NaN,NaN,NaN,NaN
52,2023-01-01,2023-Q1,2023,Q1,NaN,626542,26500.40000,844.739785,199,183,199,101,NaN,NaN,NaN,NaN,NaN
53,2023-04-01,2023-Q2,2023,Q2,NaN,650095,26648.90000,518.570168,199,184,186,100,NaN,NaN,NaN,NaN,NaN
54,2023-07-01,2023-Q3,2023,Q3,NaN,653876,26821.60000,462.301206,213,197,202,91,NaN,NaN,NaN,NaN,NaN
55,2023-10-01,2023-Q4,2023,Q4,NaN,690960,26656.96667,432.219848,212,196,209,96,NaN,NaN,NaN,NaN,NaN

### Drop any unused columns here

In [2]:
df = df.drop(['Electricity'], axis=1)

### Add any data files that need to be merged
If the column names in the data file doesn't match the master file, put the source column name as the key and target column name in the value of the dict. If renaming is not required leave the key and value the same. The renaming will happen according to the columns dict.

In [3]:
add_columns_from_file('../data/transformed/electricity_prices.csv', {'electricity_price': 'electricity_price'})

## Write the updated master table
Check the preview below to check the file is correct.

In [4]:
df.to_csv('../data/master_latest.csv', index=False)
df

,quarter,Time Period,Year,Quarter Label,Total Demand,"GDP (AUD, Millions)","Population (000,s)",Coal_Price (PCOALAUUSDM),Premium unleaded petrol (95 RON) (cpl),Regular unleaded petrol (91 RON) (cpl),Automotive diesel (cpl),Automotive LPG (cpl),Temperature(max),Temperature(avg),Temperature(min),Renewables?,electricity_price
0,2010-01-01,2010-Q1,2010,Q1,49239561.29,314838,21964.10000,298.402058,136,126,125,62,29.94,23.83,18.54,NaN,NaN
1,2010-04-01,2010-Q2,2010,Q2,48247671.02,340575,22031.80000,317.381417,139,129,130,60,25.88,16.52,8.35,NaN,NaN
2,2010-07-01,2010-Q3,2010,Q3,50211015.42,345512,22104.40000,299.825672,135,124,128,54,22.98,15.06,8.13,NaN,NaN
3,2010-10-01,2010-Q4,2010,Q4,46514896.77,365403,22172.50000,339.576623,136,126,129,61,26.73,20.49,13.94,NaN,NaN
4,2011-01-01,2011-Q1,2011,Q1,48217913.16,341094,22268.80000,411.589309,148,137,142,73,29.44,23.65,18.63,NaN,NaN
5,2011-04-01,2011-Q2,2011,Q2,47830283.50,366641,22340.00000,387.850465,154,143,151,72,24.27,15.71,8.20,NaN,NaN
6,2011-07-01,2011-Q3,2011,Q3,48616230.64,372918,22432.80000,387.013149,152,142,146,69,23.50,14.46,6.96,NaN,NaN
7,2011-10-01,2011-Q4,2011,Q4,46137155.50,388419,22522.20000,368.834476,154,142,149,68,27.91,20.66,13.42,NaN,NaN
8,2012-01-01,2012-Q1,2012,Q1,47188663.11,358492,22640.90000,362.203525,156,145,150,75,28.16,22.67,17.48,NaN,NaN
9,2012-04-01,2012-Q2,2012,Q2,47011290.32,381023,22733.50000,306.927939,158,146,152,73,25.10,16.15,9.18,NaN,NaN
10,2012-07-01,2012-Q3,2012,Q3,47265632.34,379954,22833.90000,278.002062,152,139,146,63,24.27,14.74,6.52,NaN,NaN
11,2012-10-01,2012-Q4,2012,Q4,44883583.47,396614,22928.00000,270.181174,153,142,150,75,28.90,21.37,12.71,NaN,NaN
12,2013-01-01,2013-Q1,2013,Q1,46260200.22,369661,23043.00000,294.616218,155,145,150,70,29.80,23.27,18.03,NaN,NaN
13,2013-04-01,2013-Q2,2013,Q2,45318185.12,391216,23128.10000,276.001862,151,141,146,64,23.49,15.62,9.10,NaN,NaN
14,2013-07-01,2013-Q3,2013,Q3,45310078.97,393042,23220.20000,247.739707,160,150,155,73,24.44,15.29,7.89,NaN,NaN
15,2013-10-01,2013-Q4,2013,Q4,43773951.40,416029,23297.80000,263.251363,159,148,159,80,27.05,20.24,13.07,NaN,NaN
16,2014-01-01,2014-Q1,2014,Q1,45397804.12,386882,23406.20000,250.754279,165,154,161,89,28.89,22.79,17.41,NaN,NaN
17,2014-04-01,2014-Q2,2014,Q2,44165717.94,403742,23475.70000,234.703826,162,151,158,77,24.70,16.69,9.65,NaN,NaN
18,2014-07-01,2014-Q3,2014,Q3,45631896.93,402117,23562.90000,219.812086,157,147,155,74,22.17,14.02,6.16,NaN,NaN
19,2014-10-01,2014-Q4,2014,Q4,43431682.43,421533,23640.30000,203.477587,147,136,147,70,27.22,20.97,13.17,NaN,NaN
20,2015-01-01,2015-Q1,2015,Q1,44809031.10,392282,23745.60000,203.720401,131,120,129,60,28.47,22.65,17.22,32236.09400,42.7500
21,2015-04-01,2015-Q2,2015,Q2,44813067.37,408800,23816.00000,189.973805,148,136,132,59,22.92,15.50,8.78,33778.54600,46.7500
22,2015-07-01,2015-Q3,2015,Q3,46485333.26,411271,23904.30000,189.641866,146,133,130,56,21.36,13.68,6.74,35320.99800,50.7500
23,2015-10-01,2015-Q4,2015,Q4,44420746.58,427741,23984.60000,168.974559,137,125,126,59,27.96,21.09,13.98,36863.45000,54.7500
24,2016-01-01,2016-Q1,2016,Q1,46522035.50,398018,24103.40000,162.645765,137,112,114,60,29.20,23.03,18.13,38405.90200,58.7500
25,2016-04-01,2016-Q2,2016,Q2,44955022.24,421906,24190.90000,165.414388,128,119,115,62,25.90,17.07,9.90,37773.44275,68.0625
26,2016-07-01,2016-Q3,2016,Q3,46444310.88,423729,24297.50000,212.119179,127,115,118,59,21.61,14.86,8.80,37140.98350,77.3750
27,2016-10-01,2016-Q4,2016,Q4,43689492.06,456348,24385.10000,300.802345,134,123,124,64,28.50,20.69,11.76,36508.52425,86.6875
28,2017-01-01,2017-Q1,2017,Q1,46455202.23,429749,24511.40000,263.727626,141,130,130,71,30.15,23.84,18.90,35876.06500,96.0000
29,2017-04-01,2017-Q2,2017,Q2,44302363.68,449551,24592.60000,255.902458,138,126,128,70,23.74,15.88,9.15,38437.75625,95.0000
30,2017-07-01,2017-Q3,2017,Q3,45706381.00,451969,24690.10000,298.321382,135,123,126,68,23.94,14.50,6.64,40999.44750,94.0000
31,2017-10-01,2017-Q4,2017,Q4,43660453.74,472305,24759.00000,311.705485,149,136,133,77,28.68,20.92,14.31,43561.13875,93.0000
32,2018-01-01,2018-Q1,2018,Q1,45642401.29,446656,24881.80000,329.138013,149,136,139,80,29.77,23.12,17.83,46122.83000,92.0000
33,2018-04-01,2018-Q2,2018,Q2,44982003.65,473598,24963.30000,330.122883,159,146,149,78,25.47,16.18,8.02,47630.73525,95.6875
34,2018-07-01,2018-Q3,2018,Q3,45694022.87,476753,25067.40000,371.049886,159,148,154,80,21.69,14.02,6.14,49138.64050,99.3750
35,2018-10-01,2018-Q4,2018,Q4,43150248.30,501374,25146.10000,328.458643,155,143,157,83,28.05,20.71,13.81,50646.54575,103.0625
36,2019-01-01,2019-Q1,2019,Q1,46330705.49,471736,25264.90000,306.428339,143,131,143,72,30.21,23.63,18.32,52154.45100,106.7500
37,2019-04-01,2019-Q2,2019,Q2,44227126.72,500179,25334.80000,255.958750,159,146,149,76,24.82,16.28,8.93,54429.86425,98.3125
38,2019-07-01,2019-Q3,2019,Q3,45208703.31,503289,25438.10000,214.543767,156,142,146,72,23.28,14.51,7.68,56705.27750,89.8750
39,2019-10-01,2019-Q4,2019,Q4,42916303.02,522443,25520.50000,209.387979,164,150,148,71,28.81,20.87,12.93,58980.69075,81.4375
40,2020-01-01,2020-Q1,2020,Q1,44723503.36,488115,25627.90000,213.361218,154,139,145,77,29.05,22.65,16.74,61256.10400,73.0000
41,2020-04-01,2020-Q2,2020,Q2,43321142.35,470751,25649.20000,173.771068,125,110,120,70,24.93,15.72,8.32,64578.20875,69.8750
42,2020-07-01,2020-Q3,2020,Q3,44607685.65,488221,25633.30000,155.060387,137,123,118,70,22.74,14.50,7.97,67900.31350,66.7500
43,2020-10-01,2020-Q4,2020,Q4,41565582.03,531962,25630.70000,201.605705,139,123,117,69,27.33,20.66,13.45,71222.41825,63.6250
44,2021-01-01,2021-Q1,2021,Q1,36153608.61,513235,25653.00000,278.711972,149,134,126,76,27.84,22.06,17.53,74544.52300,60.5000
45,2021-04-01,2021-Q2,2021,Q2,NaN,555484,25685.40000,334.207743,159,143,135,80,NaN,NaN,NaN,77185.01025,79.8125
46,2021-07-01,2021-Q3,2021,Q3,NaN,547326,25704.00000,514.889471,169,153,145,82,NaN,NaN,NaN,79825.49750,99.1250
47,2021-10-01,2021-Q4,2021,Q4,NaN,590493,25771.40000,600.007746,180,164,160,96,NaN,NaN,NaN,82465.98475,118.4375
48,2022-01-01,2022-Q1,2022,Q1,NaN,572077,25909.90000,857.687492,197,182,182,101,NaN,NaN,NaN,85106.47200,137.7500
49,2022-04-01,2022-Q2,2022,Q2,NaN,623325,26014.40000,1180.637111,204,189,206,101,NaN,NaN,NaN,NaN,139.4375
50,2022-07-01,2022-Q3,2022,Q3,NaN,624333,26161.80000,1348.857769,195,180,210,96,NaN,NaN,NaN,NaN,141.1250
51,2022-10-01,2022-Q4,2022,Q4,NaN,662870,26312.20000,1222.854427,199,184,222,95,NaN,NaN,NaN,NaN,142.8125
52,2023-01-01,2023-Q1,2023,Q1,NaN,626542,26500.40000,844.739785,199,183,199,101,NaN,NaN,NaN,NaN,144.5000
53,2023-04-01,2023-Q2,2023,Q2,NaN,650095,26648.90000,518.570168,199,184,186,100,NaN,NaN,NaN,NaN,NaN
54,2023-07-01,2023-Q3,2023,Q3,NaN,653876,26821.60000,462.301206,213,197,202,91,NaN,NaN,NaN,NaN,NaN
55,2023-10-01,2023-Q4,2023,Q4,NaN,690960,26656.96667,432.219848,212,196,209,96,NaN,NaN,NaN,NaN,NaN

### Normalise values

In [8]:
normalised_df = df.drop(['Time Period', 'Year', 'Quarter Label'], axis=1).set_index('quarter')
normalised_df = (normalised_df-normalised_df.min())/(normalised_df.max()-normalised_df.min())
normalised_df.to_csv('../data/master_normalised.csv')
normalised_df

,Total Demand,"GDP (AUD, Millions)","Population (000,s)",Coal_Price (PCOALAUUSDM),Premium unleaded petrol (95 RON) (cpl),Regular unleaded petrol (91 RON) (cpl),Automotive diesel (cpl),Automotive LPG (cpl),Temperature(max),Temperature(avg),Temperature(min),Renewables?,electricity_price
quarter,,,,,,,,,,,,,
2010-01-01,0.930894,0.000000,0.000000,0.120072,0.125000,0.183908,0.101852,0.170213,0.969492,0.999016,0.971787,NaN,NaN
2010-04-01,0.860334,0.068427,0.013937,0.135970,0.159091,0.218391,0.148148,0.127660,0.510734,0.279528,0.173197,NaN,NaN
2010-07-01,1.000000,0.081553,0.028883,0.121265,0.113636,0.160920,0.129630,0.000000,0.183051,0.135827,0.155956,NaN,NaN
2010-10-01,0.737070,0.134438,0.042903,0.154562,0.125000,0.183908,0.138889,0.148936,0.606780,0.670276,0.611285,NaN,NaN
2011-01-01,0.858217,0.069807,0.062728,0.214885,0.261364,0.310345,0.259259,0.404255,0.912994,0.981299,0.978840,NaN,NaN
2011-04-01,0.830642,0.137729,0.077385,0.195000,0.329545,0.379310,0.342593,0.382979,0.328814,0.199803,0.161442,NaN,NaN
2011-07-01,0.886552,0.154418,0.096490,0.194298,0.306818,0.367816,0.296296,0.319149,0.241808,0.076772,0.064263,NaN,NaN
2011-10-01,0.710198,0.195631,0.114894,0.179071,0.329545,0.367816,0.324074,0.297872,0.740113,0.687008,0.570533,NaN,NaN
2012-01-01,0.784999,0.116063,0.139331,0.173516,0.352273,0.402299,0.333333,0.446809,0.768362,0.884843,0.888715,NaN,NaN
2012-04-01,0.772382,0.175967,0.158394,0.127214,0.375000,0.413793,0.351852,0.404255,0.422599,0.243110,0.238245,NaN,NaN
2012-07-01,0.790475,0.173125,0.179063,0.102984,0.306818,0.333333,0.296296,0.191489,0.328814,0.104331,0.029781,NaN,NaN
2012-10-01,0.621023,0.217419,0.198435,0.096432,0.318182,0.367816,0.333333,0.446809,0.851977,0.756890,0.514890,NaN,NaN
2013-01-01,0.718951,0.145759,0.222110,0.116901,0.340909,0.402299,0.333333,0.340426,0.953672,0.943898,0.931818,NaN,NaN
2013-04-01,0.651939,0.203067,0.239629,0.101308,0.295455,0.356322,0.296296,0.212766,0.240678,0.190945,0.231975,NaN,NaN
2013-07-01,0.651363,0.207922,0.258590,0.077634,0.397727,0.459770,0.379630,0.404255,0.348023,0.158465,0.137147,NaN,NaN
2013-10-01,0.542087,0.269038,0.274565,0.090628,0.386364,0.436782,0.416667,0.553191,0.642938,0.645669,0.543103,NaN,NaN
2014-01-01,0.657603,0.191544,0.296881,0.080159,0.454545,0.505747,0.435185,0.744681,0.850847,0.896654,0.883229,NaN,NaN
2014-04-01,0.569956,0.236370,0.311189,0.066714,0.420455,0.471264,0.407407,0.489362,0.377401,0.296260,0.275078,NaN,NaN
2014-07-01,0.674256,0.232050,0.329141,0.054240,0.363636,0.425287,0.379630,0.425532,0.091525,0.033465,0.001567,NaN,NaN
2014-10-01,0.517739,0.283671,0.345075,0.040557,0.250000,0.298851,0.305556,0.340426,0.662147,0.717520,0.550940,NaN,NaN
2015-01-01,0.615720,0.205901,0.366752,0.040761,0.068182,0.114943,0.138889,0.127660,0.803390,0.882874,0.868339,0.000000,0.000000
2015-04-01,0.616007,0.249818,0.381245,0.029246,0.261364,0.298851,0.166667,0.106383,0.176271,0.179134,0.206897,0.029174,0.039312
2015-07-01,0.734967,0.256388,0.399424,0.028968,0.238636,0.264368,0.148148,0.042553,0.000000,0.000000,0.047022,0.058348,0.078624
2015-10-01,0.588098,0.300177,0.415955,0.011655,0.136364,0.172414,0.111111,0.106383,0.745763,0.729331,0.614420,0.087523,0.117936
2016-01-01,0.737577,0.221152,0.440412,0.006354,0.136364,0.022989,0.000000,0.127660,0.885876,0.920276,0.939655,0.116697,0.157248
2016-04-01,0.626105,0.284663,0.458425,0.008673,0.034091,0.103448,0.009259,0.170213,0.512994,0.333661,0.294671,0.104734,0.248771
2016-07-01,0.732048,0.289510,0.480371,0.047796,0.022727,0.057471,0.037037,0.106383,0.028249,0.116142,0.208464,0.092772,0.340295
2016-10-01,0.536079,0.376234,0.498405,0.122083,0.102273,0.149425,0.092593,0.212766,0.806780,0.689961,0.440439,0.080810,0.431818
2017-01-01,0.732823,0.305515,0.524406,0.091027,0.181818,0.229885,0.148148,0.361702,0.993220,1.000000,1.000000,0.068847,0.523342
2017-04-01,0.579677,0.358163,0.541122,0.084472,0.147727,0.183908,0.129630,0.340426,0.268927,0.216535,0.235893,0.117299,0.513514
2017-07-01,0.679554,0.364592,0.561194,0.120004,0.113636,0.149425,0.111111,0.297872,0.291525,0.080709,0.039185,0.165752,0.503686
2017-10-01,0.534014,0.418659,0.575378,0.131216,0.272727,0.298851,0.175926,0.489362,0.827119,0.712598,0.640282,0.214204,0.493857
2018-01-01,0.675003,0.350466,0.600659,0.145818,0.272727,0.298851,0.231481,0.553191,0.950282,0.929134,0.916144,0.262656,0.484029
2018-04-01,0.628024,0.422097,0.617437,0.146643,0.386364,0.413793,0.324074,0.510638,0.464407,0.246063,0.147335,0.291177,0.520270
2018-07-01,0.678675,0.430485,0.638868,0.180926,0.386364,0.436782,0.370370,0.553191,0.037288,0.033465,0.000000,0.319698,0.556511
2018-10-01,0.497719,0.495945,0.655069,0.145249,0.340909,0.379310,0.398148,0.617021,0.755932,0.691929,0.601097,0.348219,0.592752
2019-01-01,0.723967,0.417147,0.679527,0.126795,0.204545,0.241379,0.268519,0.382979,1.000000,0.979331,0.954545,0.376739,0.628993
2019-04-01,0.574325,0.492768,0.693917,0.084519,0.386364,0.413793,0.324074,0.468085,0.390960,0.255906,0.218652,0.419777,0.546069
2019-07-01,0.644151,0.501037,0.715183,0.049827,0.352273,0.367816,0.296296,0.382979,0.216949,0.081693,0.120690,0.462815,0.463145
2019-10-01,0.481077,0.551962,0.732146,0.045508,0.443182,0.459770,0.314815,0.361702,0.841808,0.707677,0.532132,0.505852,0.380221
2020-01-01,0.609636,0.460694,0.754256,0.048836,0.329545,0.333333,0.287037,0.489362,0.868927,0.882874,0.830721,0.548890,0.297297
2020-04-01,0.509876,0.414528,0.758641,0.015673,0.000000,0.000000,0.055556,0.340426,0.403390,0.200787,0.170846,0.611725,0.266585
2020-07-01,0.601397,0.460975,0.755368,0.000000,0.136364,0.149425,0.037037,0.340426,0.155932,0.080709,0.143417,0.674560,0.235872
2020-10-01,0.384991,0.577270,0.754833,0.038989,0.159091,0.149425,0.027778,0.319149,0.674576,0.687008,0.572884,0.737394,0.205160
2021-01-01,0.000000,0.527480,0.759424,0.103578,0.272727,0.275862,0.111111,0.468085,0.732203,0.824803,0.892633,0.800229,0.174447
2021-04-01,NaN,0.639808,0.766094,0.150065,0.386364,0.379310,0.194444,0.553191,NaN,NaN,NaN,0.850172,0.364251
2021-07-01,NaN,0.618119,0.769923,0.301416,0.500000,0.494253,0.287037,0.595745,NaN,NaN,NaN,0.900115,0.554054
2021-10-01,NaN,0.732887,0.783798,0.372716,0.625000,0.620690,0.425926,0.893617,NaN,NaN,NaN,0.950057,0.743857
2022-01-01,NaN,0.683924,0.812311,0.588565,0.818182,0.827586,0.629630,1.000000,NaN,NaN,NaN,1.000000,0.933661
2022-04-01,NaN,0.820178,0.833824,0.859088,0.897727,0.908046,0.851852,1.000000,NaN,NaN,NaN,NaN,0.950246
2022-07-01,NaN,0.822858,0.864169,1.000000,0.795455,0.804598,0.888889,0.893617,NaN,NaN,NaN,NaN,0.966830
2022-10-01,NaN,0.925317,0.895131,0.894452,0.840909,0.850575,1.000000,0.872340,NaN,NaN,NaN,NaN,0.983415
2023-01-01,NaN,0.828731,0.933875,0.577719,0.840909,0.839080,0.787037,1.000000,NaN,NaN,NaN,NaN,1.000000
2023-04-01,NaN,0.891352,0.964447,0.304499,0.840909,0.850575,0.666667,0.978723,NaN,NaN,NaN,NaN,NaN
2023-07-01,NaN,0.901404,1.000000,0.257364,1.000000,1.000000,0.814815,0.787234,NaN,NaN,NaN,NaN,NaN
2023-10-01,NaN,1.000000,0.966107,0.232166,0.988636,0.988506,0.879630,0.893617,NaN,NaN,NaN,NaN,NaN